-- Seed the global course catalog with preloaded data
INSERT INTO course_catalog (code, name, credits) VALUES
                                                     ('CHE110', 'Environmental Studies', 4),
                                                     ('CSE111', 'Orientation to Computing-I', 2),
                                                     ('CSE326', 'Internet Programming Laboratory', 2),
                                                     ('ECE249', 'Basic Electrical and Electronics Engineering', 4),
                                                     ('ECE279', 'Basic Electrical and Electronics Engineering Laboratory', 1),
                                                     ('INT108', 'Python Programming', 4),
                                                     ('MTH174', 'Engineering Mathematics', 4),
                                                     ('PES318', 'Soft Skills-I', 3),
                                                     ('CSE101', 'Computer Programming', 3),
                                                     ('CSE121', 'Orientation to Computing-II', 1),
                                                     ('CSE320', 'Software Engineering', 3),
                                                     ('INT306', 'Database Management Systems', 4),
                                                     ('MEC135', 'Basics of Mechanical Engineering', 3),
                                                     ('MTH401', 'Discrete Mathematics', 3),
                                                     ('PEL125', 'Upper Intermediate Communication Skills-I', 3),
                                                     ('PHY110', 'Engineering Physics', 3),
                                                     ('CSE202', 'Object Oriented Programming', 4),
                                                     ('CSE205', 'Data Structures and Algorithms', 4),
                                                     ('CSE211', 'Computer Organization and Design', 4),
                                                     ('CSE306', 'Computer Networks', 3),
                                                     ('CSE307', 'Internetworking Essentials', 1),
                                                     ('GEN231', 'Community Development Project', 2),
                                                     ('MTHxxx', 'Probability and Statistics', 3),
                                                     ('PEL136', 'Advanced Communication Skills-II', 3),
                                                     ('CSE310', 'Programming in Java', 4),
                                                     ('CSE316', 'Operating Systems', 3),
                                                     ('CSE325', 'Operating Systems Laboratory', 1),
                                                     ('CSE408', 'Design and Analysis of Algorithms', 3),
                                                     ('INT217', 'Introduction to Data Management', 3),
                                                     ('INT232', 'Data Science Toolbox: R Programming', 3),
                                                     ('INT426', 'Generative Artificial Intelligence', 3),
                                                     ('PEA305', 'Analytical Skills-I', 3),
                                                     ('CSE322', 'Formal Languages and Automation Theory', 3),
                                                     ('CSE343', 'Training in Programming', 3),
                                                     ('INT233', 'Data Visualization', 3),
                                                     ('INT234', 'Predictive Analytics', 3),
                                                     ('JAP105', 'Basic Japanese-I', 3),
                                                     ('PEA306', 'Analytical Skills-II', 3),
                                                     ('PELxxx', 'Upper-Intermediate Verbal Ability', 3),
                                                     ('CSE332', 'Industry Ethics and Legal Issues', 2),
                                                     ('CSE358', 'Combinatorial Studies', 4),
                                                     ('CSE393', 'Online Academic Course', 3),
                                                     ('INT312', 'Big Data Fundamentals', 3),
                                                     ('JAP106', 'Basic Japanese-II', 3),
                                                     ('PES319', 'Soft Skills-II', 3)
    ON CONFLICT DO NOTHING;
